targets:
  $default:
    builders:
      source_gen|combining_builder:
        generate_for:
          - lib/**.dart
        options:
          build_extensions:
            '^lib/domain/entity/{{}}.dart': 'lib/data/model/{{}}.g.dart'
      freezed|freezed:
        enabled: true
        options:
          build_extensions:
            '^lib/domain/entity/{{}}.dart': 'lib/data/model/{{}}.freezed.dart'
